# 9. void의 두 가지 사용법, declare, void vs undefined

void는 return 값을 사용안겠다는 뜻이긴 한데, 함수 리턴값 선언, 함수 메서드로 선언, 인자값으로 선언 이렇게 세가지로 쓰임이 나뉠 수 있다.



그리고 함수 리턴값에 사용은 리턴값을 사용하지 않겠다에 아예 리턴 값이 없어야 하는 내용이 포함이 되고 <mark style="background-color:orange;">(이 부분은 최신 5.x ts 업데이트에 변동 내용이 있음)</mark>



나머지 둘은 리턴값을 사용하지 않겠다만 적용이 된다.



* 일반적인 함수에 선언할 때

```typescript
function a(): void {
    // return undefined; or return ;
}
```

return undefined, ; 는 됨.



* method 로 선언할 때

```typescript
interface A {
    talk: () => void;
}
const a: A = {
    talk() { return 3; }
}
```

메서드 안에서는 return 이 존재해도 됨.

대신 실제로 js처럼 return 값이 처리되는 것은 아님 void가 이걸 무시해버림.

아마도 void의 기능은 return값이 없어야하는게 맞았을거야 그러나 맨 아래의 총정리 예제 같은 경우 때문에 눈물을 머금고 가능하게 허용했을것.



* 인자값(파라미터, 매개변수)로 사용할 때

```typescript
function a(callback: () => void): void {

}

a(() => {
    return '3';
})
```

메서드 안에서는 return 이 존재해도 됨.



추가로 타입만 선언하고 싶을 때는 declare를 쓸 수 있다. (js로 변환시 구현부 없이도 그냥 사라진다.)

declare는 다른 js 페이지들을 왔다갔다 하면서 자주 사용된다.

저기에 선언된 타입을 여기서 보증하거나 등등

```typescript
declare const a: string;
declare function a(x: number): number;
declare class A {}

// 추후 declare module, declare global, declare namespace도 배움
```



총정리 설명으로 다음과 같은 forEach 함수를 선언했다.

```typescript
declare function forEach(arr: number[], callback: (el: number) => undefined): void;

let target: number[] = [];
forEach([1,2,3], el => { target.push(el) });
forEach([1,2,3], el => target.push(el));
```

여기에서 callback 함수의 return type은 undefined으로 되어있다.

지금까지 말한 매개변수의 함수에 void가 아닌 값이 들어갔다.

이게 문제인건 아니지만 여러가지 고려해야할 것들이 많이 발생한다.

어떻게 보면 void가 이 이 안에 들어갔을때 왜 저런 다른 역할들을 부여 받았는지를 이유를 여기서 찾을 수 있을 것 같다.



아무튼 위와 같이 하면 forEach 실행문 둘다 에러를 발생시키는데 두 에러의 내용이 다르다.

첫번째 실행문 에러

<figure><img src="../../.gitbook/assets/image.png" alt=""><figcaption></figcaption></figure>

두번째 실행문 에러

<figure><img src="../../.gitbook/assets/image (8).png" alt=""><figcaption></figcaption></figure>

첫번째,  두번째 실행문은 return 값이 없는 상태(void)로 push라는 함수가 실행이 되었다.&#x20;

고로 'Type 'void' is not assignable to type 'undefined' forEach함수의 타입을 선언 했을때 push에 해당하는 함수의 return 값으로 undefined를 선언했기에 undefined에 void가 대입될 수 없다는 말이다.

\=> 최신 이해하는 말로 push의 return 값은 값을 넣은 number 가 된다. (target 에도 number가 추가된다)

\=> 그렇기 때문에 undefined로 정의한 부분에 에러가 발생함.



\=> 그래서 number로 바꿔보았다.

두번째, 첫번째 실행문은 return 값이 target.push(el)로 되는데(화살표함수문법) 이렇게 되면 위에서 target의 타입을 number\[]로 선언했기에 나오는 type인 number 가 기존 forEach 함수 타입의 undefined에 대입되면서 에러가 발생한다.



또한, 뭐 undefined를 number로 바꿔도 둘중에 하나가 문제가 발생 고로.

함수를 다양하게 활용하면서 그 안에 들어가는 callback 함수는 결국 void로 찾아가는 경우가 많다는 것.

왜냐하면 return 으로 값을 넣어도 되고 없어도 되니까.&#x20;

아무튼 이런 문제로 인해 매개변수로 들어가는, 메서드로 사용되는   함수에는 void의 기능이 조금 다르게 형성되었다.



> void가 undefined랑 다르다! 고로 잘 구분해서 사용해야함.



